% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage[french]{babel}
\usepackage{booktabs}
\usepackage{float}
\usepackage{xcolor}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\textcolor{gray}{\small ENSAE ISE 1 -- Projet Statistique 2025-2026}}
\fancyhead[R]{\textcolor{gray}{\small Nigeria GHS Panel -- Wave 4}}
\fancyfoot[C]{\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\definecolor{bleuensae}{RGB}{26,82,118}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Analyse 1 --- Profil demographique des menages nigerians},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Analyse 1 --- Profil demographique des menages nigerians}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Nigeria GHS Panel -- Wave 4 (2018) \textbar{} ENSAE ISE 1 --
2025-2026}
\author{ANDRIALALAOSOA Marcellin\\
Andil Ben Andjiboudine}
\date{17 mars 2026}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\textcolor{bleuensae}{\textbf{Objectif :}} Décrire la composition et les
caractéristiques démographiques des ménages enquêtés dans la Wave 4
(2018) du GHS Panel à partir de la section \texttt{sect1\_harvestw4}.

\textcolor{bleuensae}{\textbf{Fichier utilisé :}}
\texttt{sect1\_harvestw4.dta} \textbar{}
\textcolor{bleuensae}{\textbf{Variables clés :}} \texttt{hhid},
\texttt{indiv}, \texttt{s1q2} (sexe), \texttt{s1q3} (lien de parenté),
\texttt{s1q4} (âge), \texttt{sector} (zone rurale/urbaine)

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Exploration et qualité des
données}\label{exploration-et-qualituxe9-des-donnuxe9es}

\subsection{Dimensions du fichier}\label{dimensions-du-fichier}

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{lc}
\caption{\label{tab:dimensions}Dimensions et qualite du fichier sect1\_harvestw4}\\
\toprule
\cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Description}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Valeur}}}\\
\midrule
\cellcolor{gray!10}{Nombre d'observations} & \cellcolor{gray!10}{30 337}\\
Nombre de variables & 65\\
\cellcolor{gray!10}{Menages uniques} & \cellcolor{gray!10}{4 980}\\
Valeurs manquantes -- Age (s1q4) & 3 780\\
\cellcolor{gray!10}{Valeurs manquantes -- Sexe (s1q2)} & \cellcolor{gray!10}{3 780}\\
\bottomrule
\end{longtable}
\endgroup{}

Le fichier \texttt{sect1\_harvestw4} contient \textbf{30 337
observations} réparties sur \textbf{4980 ménages} distincts. Chaque
ligne correspond à un membre individuel d'un ménage enquêté lors de la
visite Post-Harvest de la Wave 4 (2018). On dénombre \textbf{3780
valeurs manquantes} sur l'âge et \textbf{3780} sur le sexe, ce qui reste
marginal au regard de la taille totale de l'échantillon.

\subsection{Vérification des
doublons}\label{vuxe9rification-des-doublons}

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{lcl}
\caption{\label{tab:doublons}Verification des doublons sur l'identifiant individuel}\\
\toprule
\cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Verification}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Nombre}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Statut}}}\\
\midrule
\cellcolor{gray!10}{Doublons sur (hhid + indiv)} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{OK -- Aucun doublon detecte}\\
\bottomrule
\end{longtable}
\endgroup{}

Le fichier est \textbf{exempt de doublons} : chaque individu est
identifié de manière unique par la combinaison hhid + indiv. Cette
vérification préliminaire garantit l'intégrité des analyses ultérieures.

\subsection{Carte des valeurs
manquantes}\label{carte-des-valeurs-manquantes}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{D:/ENSAE/ISE_1_SEMESTRE_2/R/mon_projet/rapport/Analyse1_Profil_Demographique_files/figure-latex/vis-miss-1} 

}

\caption{Carte des valeurs manquantes -- variables demographiques cles (Wave 4)}\label{fig:vis-miss}
\end{figure}

La carte des valeurs manquantes offre une vision synthétique de la
complétude des variables démographiques clés. Les variables
\texttt{hhid} et \texttt{indiv} (identifiants) sont complètes à 100\%,
ce qui est attendu. La variable \texttt{s1q3} (lien de parenté) présente
le taux de valeurs manquantes le plus élevé, ce qui peut s'expliquer par
des refus de réponse ou des situations familiales difficiles à
classifier. Ces lacunes devront être prises en compte dans les analyses
de fréquences du lien de parenté.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Analyse univariée de
l'âge}\label{analyse-univariuxe9e-de-luxe2ge}

\subsection{Statistiques descriptives}\label{statistiques-descriptives}

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{ccccccccc}
\caption{\label{tab:age-stats-table}Statistiques descriptives de l'age des membres du menage (Wave 4)}\\
\toprule
\cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Moyenne}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Mediane}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Q1}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Q3}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Min}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Max}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Ecart-type}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{CV (\%)}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Asymetrie}}}\\
\midrule
\cellcolor{gray!10}{23.98} & \cellcolor{gray!10}{18} & \cellcolor{gray!10}{8} & \cellcolor{gray!10}{36} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{130} & \cellcolor{gray!10}{19.73} & \cellcolor{gray!10}{82.27} & \cellcolor{gray!10}{0.91}\\
\bottomrule
\end{longtable}
\endgroup{}

L'âge moyen des membres des ménages enquêtés est de \textbf{24 ans},
avec une médiane de \textbf{18 ans}. L'écart entre la moyenne et la
médiane indique une distribution légèrement asymétrique. L'interquartile
s'étend de \textbf{8} à \textbf{36 ans}, reflétant la concentration de
la population dans les tranches jeunes. Le coefficient de variation
(\textbf{CV = 82.3\%}) traduit une dispersion très forte des âges,
caractéristique des populations à forte fécondité où coexistent de
nombreux enfants et des adultes d'âges très variés.

\subsection{Histogramme et boxplot}\label{histogramme-et-boxplot}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{D:/ENSAE/ISE_1_SEMESTRE_2/R/mon_projet/rapport/Analyse1_Profil_Demographique_files/figure-latex/histogramme-boxplot-1} 

}

\caption{Distribution et dispersion de l'age des membres du menage -- Wave 4}\label{fig:histogramme-boxplot}
\end{figure}

L'histogramme confirme la structure jeune de la population nigériane :
les tranches d'âge 0-4 et 5-9 ans sont les plus représentées, formant
une base large caractéristique des populations à forte fécondité. La
distribution est \textbf{asymétrique à droite} (queue vers les âges
élevés), avec un effilement progressif à partir de 30 ans. Le boxplot
met en évidence plusieurs valeurs aberrantes aux âges très élevés
(au-delà de 90 ans), qui pourraient correspondre à des erreurs de
déclaration ou à de rares cas de grande longévité. La ligne rouge
(moyenne) est légèrement décalée vers la droite par rapport à la ligne
verte (médiane), confirmant l'asymétrie positive de la distribution.

\subsection{Test de normalité de
Shapiro-Wilk}\label{test-de-normalituxe9-de-shapiro-wilk}

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{lcccc}
\caption{\label{tab:shapiro-table}Resultat du test de normalite de Shapiro-Wilk sur l'age}\\
\toprule
\cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Taille.echantillon}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Statistique.W}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{p.valeur}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Conclusion}}}\\
\midrule
\cellcolor{gray!10}{W} & \cellcolor{gray!10}{5000} & \cellcolor{gray!10}{0.9037} & \cellcolor{gray!10}{< 2.2e-16} & \cellcolor{gray!10}{Distribution NON normale (p < 0.05)}\\
\bottomrule
\end{longtable}
\endgroup{}

Le test de Shapiro-Wilk, réalisé sur un échantillon aléatoire de
\textbf{5000 observations} (limite technique du test), retourne une
statistique W = \textbf{0.9037} avec une p-valeur \textbf{= \textless{}
2.2e-16}. Ce résultat conduit au \textbf{rejet de l'hypothèse de
normalité} (p \textless{} 0,05) : la distribution de l'âge \textbf{n'est
pas normale}. Cette conclusion, cohérente avec l'observation visuelle de
l'histogramme, justifie pleinement le recours à des \textbf{tests non
paramétriques} (Wilcoxon, Kruskal-Wallis) pour toutes les comparaisons
ultérieures impliquant cette variable.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Pyramide des âges (Wave 4)}\label{pyramide-des-uxe2ges-wave-4}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{D:/ENSAE/ISE_1_SEMESTRE_2/R/mon_projet/rapport/Analyse1_Profil_Demographique_files/figure-latex/pyramide-1} 

}

\caption{Pyramide des ages par sexe -- Wave 4, Post-Harvest (2018)}\label{fig:pyramide}
\end{figure}

La pyramide des âges de la Wave 4 présente une forme \textbf{expansive}
à base large, caractéristique des pays en voie de développement avec une
forte natalité. Les groupes d'âge 0-4 et 5-9 ans constituent les
cohortes les plus nombreuses, témoignant d'un taux de fécondité encore
élevé. Le rétrécissement progressif avec l'âge reflète une mortalité
significative aux âges adultes et une espérance de vie encore limitée.
La structure est \textbf{quasi-symétrique} entre hommes et femmes dans
les jeunes classes d'âge, avec une légère sur-représentation féminine
observée aux âges élevés (65+), phénomène classique de surmortalité
masculine. Cette structure démographique implique une forte pression sur
les services d'éducation et de santé pédiatrique, et annonce un
important dividende démographique potentiel si les jeunes cohortes
accèdent à l'éducation et à l'emploi.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Analyse du lien de
parenté}\label{analyse-du-lien-de-parentuxe9}

\subsection{Fréquences et intervalles de
confiance}\label{fruxe9quences-et-intervalles-de-confiance}

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{lcccc}
\caption{\label{tab:parente-table}Distribution du lien de parente avec IC a 95\% -- Wave 4}\\
\toprule
\cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Lien de parente}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Effectif}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Proportion (\%)}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{IC 95\% inf (\%)}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{IC 95\% sup (\%)}}}\\
\midrule
\cellcolor{gray!10}{3. OWN CHILD} & \cellcolor{gray!10}{14636} & \cellcolor{gray!10}{55.1} & \cellcolor{gray!10}{54.5} & \cellcolor{gray!10}{55.7}\\
1. HEAD & 4980 & 18.8 & 18.3 & 19.2\\
\cellcolor{gray!10}{2. SPOUSE} & \cellcolor{gray!10}{4273} & \cellcolor{gray!10}{16.1} & \cellcolor{gray!10}{15.6} & \cellcolor{gray!10}{16.5}\\
6. GRANDCHILD & 1045 & 3.9 & 3.7 & 4.2\\
\cellcolor{gray!10}{7. BROTHER/SISTER} & \cellcolor{gray!10}{487} & \cellcolor{gray!10}{1.8} & \cellcolor{gray!10}{1.7} & \cellcolor{gray!10}{2.0}\\
\addlinespace
10. PARENT & 291 & 1.1 & 1.0 & 1.2\\
\cellcolor{gray!10}{8. NIECE/NEPHEW} & \cellcolor{gray!10}{229} & \cellcolor{gray!10}{0.9} & \cellcolor{gray!10}{0.8} & \cellcolor{gray!10}{1.0}\\
4. STEP CHILD & 192 & 0.7 & 0.6 & 0.8\\
\cellcolor{gray!10}{9. BROTHER/SISTER-IN-LAW} & \cellcolor{gray!10}{137} & \cellcolor{gray!10}{0.5} & \cellcolor{gray!10}{0.4} & \cellcolor{gray!10}{0.6}\\
14. OTHER RELATION (SPECIFY) & 123 & 0.5 & 0.4 & 0.6\\
\addlinespace
\cellcolor{gray!10}{5. ADOPTED CHILD} & \cellcolor{gray!10}{88} & \cellcolor{gray!10}{0.3} & \cellcolor{gray!10}{0.3} & \cellcolor{gray!10}{0.4}\\
12. DOMESTIC HELP & 39 & 0.1 & 0.1 & 0.2\\
\cellcolor{gray!10}{11. PARENT-IN-LAW} & \cellcolor{gray!10}{20} & \cellcolor{gray!10}{0.1} & \cellcolor{gray!10}{0.0} & \cellcolor{gray!10}{0.1}\\
15. OTHER NON-RELATION (SPECIFY) & 17 & 0.1 & 0.0 & 0.1\\
\bottomrule
\end{longtable}
\endgroup{}

\subsection{Diagramme en barres
horizontales}\label{diagramme-en-barres-horizontales}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{D:/ENSAE/ISE_1_SEMESTRE_2/R/mon_projet/rapport/Analyse1_Profil_Demographique_files/figure-latex/parente-plot-1} 

}

\caption{Repartition du lien de parente avec le chef de menage (IC a 95\%) -- Wave 4}\label{fig:parente-plot}
\end{figure}

La catégorie \textbf{3. OWN CHILD} est la plus représentée au sein des
ménages (\textbf{55.1\%}), suivie par les \textbf{1. HEAD}
(\textbf{18.8\%}). Cette structure confirme la prédominance des
\textbf{ménages élargis} au Nigeria, où plusieurs générations cohabitent
sous le même toit. La forte proportion d'enfants dans la composition des
ménages est cohérente avec la pyramide des âges à base large observée
précédemment. Les intervalles de confiance à 95\% (calculés par la
méthode binomiale exacte) sont étroits pour les catégories les plus
fréquentes, témoignant de la précision des estimations grâce à la large
taille de l'échantillon. Les catégories moins fréquentes (belle-famille,
autre parent) présentent des IC plus larges, reflétant une moins grande
précision d'estimation.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Taille des ménages selon la zone de
résidence}\label{taille-des-muxe9nages-selon-la-zone-de-ruxe9sidence}

\subsection{Statistiques comparatives par
zone}\label{statistiques-comparatives-par-zone}

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{ccccccc}
\caption{\label{tab:taille-table}Statistiques de la taille des menages par zone de residence}\\
\toprule
\cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{zone}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{N individus}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{N menages}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Moy. taille}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Med. taille}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Min}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Max}}}\\
\midrule
\cellcolor{gray!10}{Rural} & \cellcolor{gray!10}{8719} & \cellcolor{gray!10}{1595} & \cellcolor{gray!10}{7.41} & \cellcolor{gray!10}{7} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{27}\\
Urbain & 21618 & 3385 & 8.59 & 8 & 1 & 33\\
\bottomrule
\end{longtable}
\endgroup{}

\subsection{Boxplot groupé Rural vs
Urbain}\label{boxplot-groupuxe9-rural-vs-urbain}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth]{D:/ENSAE/ISE_1_SEMESTRE_2/R/mon_projet/rapport/Analyse1_Profil_Demographique_files/figure-latex/boxplot-zone-1} 

}

\caption{Taille des menages selon la zone de residence -- Wave 4}\label{fig:boxplot-zone}
\end{figure}

\subsection{Test de Wilcoxon-Mann-Whitney et taille
d'effet}\label{test-de-wilcoxon-mann-whitney-et-taille-deffet}

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{lcccccc}
\caption{\label{tab:wilcoxon-table}Test de Wilcoxon -- Taille des menages Rural vs Urbain}\\
\toprule
\cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Test}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Med..Rural}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Med..Urbain}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{p.valeur}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{r.de.rang}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Interpretation}}}\\
\midrule
\cellcolor{gray!10}{Effect size (r)} & \cellcolor{gray!10}{Wilcoxon-Mann-Whitney} & \cellcolor{gray!10}{7} & \cellcolor{gray!10}{8} & \cellcolor{gray!10}{< 2.2e-16} & \cellcolor{gray!10}{0.151} & \cellcolor{gray!10}{Faible}\\
\bottomrule
\end{longtable}
\endgroup{}

Le boxplot révèle clairement que les \textbf{ménages ruraux sont plus
grands} que les ménages urbains. La taille médiane est de \textbf{7
membres} en milieu rural contre \textbf{8 membres} en milieu urbain,
soit un écart de \textbf{-1 membre(s)}. Le test de Wilcoxon-Mann-Whitney
confirme que cette différence est statistiquement \textbf{significative}
(p = \textless2e-16). La taille d'effet (r de rang = 0.151) est
qualifiée de \textbf{faible}, indiquant que la zone de résidence
explique une part limitée de la variabilité de la taille des ménages. Ce
résultat est cohérent avec les dynamiques socio-économiques nigérianes :
en milieu rural, la fécondité plus élevée et les structures familiales
élargies expliquent la plus grande taille des ménages, tandis qu'en
milieu urbain, le coût de la vie et les contraintes de logement
favorisent des ménages plus restreints.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Tableau récapitulatif stratifié par
zone}\label{tableau-ruxe9capitulatif-stratifiuxe9-par-zone}

\begin{table}[!h]
\centering
\caption{\label{tab:gtsummary}\textbf{Tableau 1 -- Caracteristiques demographiques par zone (Wave 4)}}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{9}{11}\selectfont
\begin{tabular}[t]{lcccc}
\toprule
\textbf{Variable} & \makecell[c]{\textbf{Overall}\ \ \\N = 30,337} & \makecell[c]{\textbf{Rural}\ \ \\N = 8,719} & \makecell[c]{\textbf{Urbain}\ \ \\N = 21,618} & \textbf{p-value}\\
\midrule
\cellcolor{gray!10}{\textbf{Age (annees)}} & \cellcolor{gray!10}{24.0 (19.7)} & \cellcolor{gray!10}{25.0 (19.4)} & \cellcolor{gray!10}{23.6 (19.8)} & \cellcolor{gray!10}{<0.001}\\
\textbf{Sexe} &  &  &  & 0.5\\
\cellcolor{gray!10}{\hspace{1em}Homme} & \cellcolor{gray!10}{13,189 (50\%)} & \cellcolor{gray!10}{3,730 (49\%)} & \cellcolor{gray!10}{9,459 (50\%)} & \cellcolor{gray!10}{}\\
\hspace{1em}Femme & 13,368 (50\%) & 3,837 (51\%) & 9,531 (50\%) & \\
\cellcolor{gray!10}{\textbf{Taille du menage}} & \cellcolor{gray!10}{8.3 (4.2)} & \cellcolor{gray!10}{7.4 (4.0)} & \cellcolor{gray!10}{8.6 (4.3)} & \cellcolor{gray!10}{<0.001}\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}\textsuperscript{1} Mean (SD); n (\%)}\\
\multicolumn{5}{l}{\rule{0pt}{1em}\textsuperscript{2} Wilcoxon rank sum test; Pearson's Chi-squared test}\\
\end{tabular}}
\end{table}

Ce tableau synthétique compare les principales caractéristiques
démographiques des ménages selon la zone de résidence (rurale vs
urbaine). Les p-valeurs issues du test de Wilcoxon pour les variables
continues (âge, taille du ménage) et du test du Chi-deux pour les
variables catégorielles (sexe) permettent d'évaluer la significativité
statistique des différences observées. La colonne ``Overall'' présente
les statistiques pour l'ensemble de l'échantillon. Ce tableau constitue
un outil de synthèse essentiel pour les décideurs et chercheurs
souhaitant comparer les profils démographiques entre milieux rural et
urbain au Nigeria.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Synthèse de l'Analyse 1}\label{synthuxe8se-de-lanalyse-1}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{5cm}>{\raggedright\arraybackslash}p{9cm}}
\caption{\label{tab:synthese}Synthese des resultats -- Analyse 1}\\
\toprule
\cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Analyse}}} & \cellcolor[HTML]{1a5276}{\textcolor{white}{\textbf{Resultat principal}}}\\
\midrule
\textbf{\cellcolor{gray!10}{Qualite des donnees (Tache 1)}} & \cellcolor{gray!10}{0 doublon(s) \&\#124; 3780 valeurs manquantes sur l'age}\\
\textbf{Distribution de l'age (Tache 2)} & Moyenne = 24 ans \&\#124; Mediane = 18 ans \&\#124; CV = 82.3\%\\
\textbf{\cellcolor{gray!10}{Normalite de l'age (Tache 2)}} & \cellcolor{gray!10}{Shapiro-Wilk W = 0.9037 \&\#124; p = <2e-16 --> Non normale}\\
\textbf{Pyramide des ages (Tache 3)} & Structure expansive \&\#124; Base large 0-14 ans \&\#124; Symetrie H/F\\
\textbf{\cellcolor{gray!10}{Lien de parente (Tache 4)}} & \cellcolor{gray!10}{3. OWN CHILD dominant (55.1\%) \&\#124; Menages elargis nigerians}\\
\addlinespace
\textbf{Taille menage Rural/Urbain (Tache 5)} & Rural med. = 7 vs Urbain = 8 \&\#124; Wilcoxon p = <2e-16 \&\#124; r = 0.151\\
\bottomrule
\end{longtabu}
\endgroup{}

L'Analyse 1 dresse un portrait démographique complet des ménages
nigérians enquêtés lors de la Wave 4 (2018). La population est
\textbf{jeune et en croissance}, avec une médiane d'âge de \textbf{18
ans} et une pyramide expansive. Les ménages ruraux sont
significativement plus grands que les ménages urbains, reflétant des
différences de fécondité et de structures familiales. La catégorie
dominante au sein des ménages est celle des \textbf{3. OWN CHILD},
confirmant la prédominance des ménages élargis intergénérationnels. Ces
caractéristiques démographiques constituent la toile de fond
indispensable pour l'interprétation des analyses d'éducation, de santé
et de bien-être économique développées dans les analyses suivantes.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\small

\textit{Rapport généré avec R 4.5.2 ---
Source : Nigeria General Household Survey Panel, Wave 4 (2018), World Bank LSMS-ISA.}

\end{document}
