# =========================================================
# 07_render_report.R
# Generation du rapport Word final
# A executer depuis la racine du projet via main.R
# =========================================================

cat("\n--- Etape 7 : Rendu du rapport Word ---\n")

# ---- 1. Packages -----------------------------------------
required <- c("rmarkdown", "officer", "knitr", "dplyr",
              "readr", "ggplot2", "scales", "tidyr", "stringr")
for (pkg in required) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org")
  }
}
library(officer)
library(rmarkdown)

# ---- 2. Chemins ------------------------------------------
project_dir <- getwd()
report_dir  <- file.path(project_dir, "report")
if (!dir.exists(report_dir)) dir.create(report_dir, recursive = TRUE)

rmd_file    <- file.path(report_dir, "rapport_analyse3.Rmd")
ref_file    <- file.path(report_dir, "reference.docx")
output_file <- file.path(report_dir, "rapport_analyse3_FINAL.docx")

# ---- 3. Creation du reference.docx -----------------------
cat("   Creation du reference.docx...\n")

ref <- read_docx()

ftr <- block_list(
  fpar(
    ftext("Page ", fp_text(font.size = 10, font.family = "Calibri",
                           color = "#444444")),
    run_word_field("PAGE"),
    ftext(" / ", fp_text(font.size = 10, font.family = "Calibri",
                         color = "#444444")),
    run_word_field("NUMPAGES"),
    fp_p = fp_par(text.align = "center", padding.bottom = 4,
                  padding.top = 4)
  )
)

ref <- body_set_default_section(
  ref,
  prop_section(
    footer_default = ftr,
    page_size    = page_size(width = 8.27, height = 11.69, orient = "portrait"),
    page_margins = page_mar(top = 1.0, bottom = 1.0, left = 1.18,
                            right = 0.79, header = 0.5, footer = 0.5, gutter = 0)
  )
)

print(ref, target = ref_file)
cat("   OK reference.docx cree\n")

# ---- 4. Ecriture du fichier .Rmd -------------------------
# On ecrit ligne par ligne avec cat() pour eviter tout
# probleme d'echappement de caracteres dans une chaine R.
cat("   Ecriture du rapport_analyse3.Rmd...\n")

con <- file(rmd_file, open = "w", encoding = "UTF-8")

cat('---', file = con, sep = "\n")
cat('title: "Analyse 3 - Acces aux services de sante et chocs sanitaires des menages"', file = con, sep = "\n")
cat('author:', file = con, sep = "\n")
cat('  - "RIRADJIM NGARMOUNDOU Tresor"', file = con, sep = "\n")
cat('  - "GUEBEDIANG A NKEN Kadidja"', file = con, sep = "\n")
cat('date: "`r format(Sys.Date(), \'%d %B %Y\')`"', file = con, sep = "\n")
cat('output:', file = con, sep = "\n")
cat('  word_document:', file = con, sep = "\n")
cat('    toc: true', file = con, sep = "\n")
cat('    toc_depth: 3', file = con, sep = "\n")
cat('    number_sections: true', file = con, sep = "\n")
cat('    reference_docx: "reference.docx"', file = con, sep = "\n")
cat('lang: fr-FR', file = con, sep = "\n")
cat('---', file = con, sep = "\n")
cat('', file = con, sep = "\n")

# ---- chunk setup ----
cat('```{r setup, include=FALSE}', file = con, sep = "\n")
cat('knitr::opts_chunk$set(', file = con, sep = "\n")
cat('  echo      = FALSE,', file = con, sep = "\n")
cat('  warning   = FALSE,', file = con, sep = "\n")
cat('  message   = FALSE,', file = con, sep = "\n")
cat('  fig.align = "center",', file = con, sep = "\n")
cat('  fig.width  = 7,', file = con, sep = "\n")
cat('  fig.height = 4.5,', file = con, sep = "\n")
cat('  dpi        = 300', file = con, sep = "\n")
cat(')', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('library(knitr)', file = con, sep = "\n")
cat('library(dplyr)', file = con, sep = "\n")
cat('library(readr)', file = con, sep = "\n")
cat('library(ggplot2)', file = con, sep = "\n")
cat('library(scales)', file = con, sep = "\n")
cat('library(tidyr)', file = con, sep = "\n")
cat('library(stringr)', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('safe_read_csv <- function(path) {', file = con, sep = "\n")
cat('  if (file.exists(path)) readr::read_csv(path, show_col_types = FALSE) else NULL', file = con, sep = "\n")
cat('}', file = con, sep = "\n")
cat('safe_read_rds <- function(path) {', file = con, sep = "\n")
cat('  if (file.exists(path)) readRDS(path) else NULL', file = con, sep = "\n")
cat('}', file = con, sep = "\n")
cat('pval_fr <- function(p) {', file = con, sep = "\n")
cat('  if (is.na(p)) return("non disponible")', file = con, sep = "\n")
cat('  if (p < 0.001) return("< 0,001")', file = con, sep = "\n")
cat('  sub("\\\\.", ",", format(round(p, 3), nsmall = 3))', file = con, sep = "\n")
cat('}', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('# Chemins : le .Rmd est compile depuis report/, ".." remonte a la racine', file = con, sep = "\n")
cat('project_dir <- normalizePath(file.path(getwd(), ".."), mustWork = FALSE)', file = con, sep = "\n")
cat('out_dir     <- file.path(project_dir, "output")', file = con, sep = "\n")
cat('tab_dir     <- file.path(out_dir, "tables")', file = con, sep = "\n")
cat('fig_dir     <- file.path(out_dir, "figures")', file = con, sep = "\n")
cat('logo_ansd   <- file.path(project_dir, "logo_structure.png")', file = con, sep = "\n")
cat('logo_ensae  <- file.path(project_dir, "logo_ecole.jpeg")', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('tab_effectifs    <- safe_read_csv(file.path(tab_dir, "table_effectifs_par_analyse.csv"))', file = con, sep = "\n")
cat('tab_missing      <- safe_read_csv(file.path(tab_dir, "table_missing_summary.csv"))', file = con, sep = "\n")
cat('tab_morbidite    <- safe_read_csv(file.path(tab_dir, "table_morbidite_sexe_age.csv"))', file = con, sep = "\n")
cat('tab_maladies     <- safe_read_csv(file.path(tab_dir, "table_top10_maladies.csv"))', file = con, sep = "\n")
cat('tab_prestataires <- safe_read_csv(file.path(tab_dir, "table_prestataires.csv"))', file = con, sep = "\n")
cat('tab_deciles      <- safe_read_csv(file.path(tab_dir, "table_deciles_depenses_sante.csv"))', file = con, sep = "\n")
cat('tab_medianes     <- safe_read_csv(file.path(tab_dir, "table_medianes_depenses_milieu.csv"))', file = con, sep = "\n")
cat('tab_outliers     <- safe_read_csv(file.path(tab_dir, "table_outliers_depenses_sante.csv"))', file = con, sep = "\n")
cat('tab_contingence  <- safe_read_csv(file.path(tab_dir, "table_contingence_consultation_quintile.csv"))', file = con, sep = "\n")
cat('tab_prop_consult <- safe_read_csv(file.path(tab_dir, "table_proportions_consultation_quintile.csv"))', file = con, sep = "\n")
cat('tab_test_consult <- safe_read_csv(file.path(tab_dir, "table_tests_consultation_quintile.csv"))', file = con, sep = "\n")
cat('tab_wilcox       <- safe_read_csv(file.path(tab_dir, "table_wilcoxon_urbain_rural.csv"))', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('fig_morbidite     <- file.path(fig_dir, "fig_morbidite_sexe_age.png")', file = con, sep = "\n")
cat('fig_maladies      <- file.path(fig_dir, "fig_top10_maladies.png")', file = con, sep = "\n")
cat('fig_prestataires  <- file.path(fig_dir, "fig_prestataires.png")', file = con, sep = "\n")
cat('fig_hist_dep      <- file.path(fig_dir, "fig_hist_depenses_log.png")', file = con, sep = "\n")
cat('fig_box_dep_prest <- file.path(fig_dir, "fig_boxplot_depenses_prestataire.png")', file = con, sep = "\n")
cat('fig_bar100        <- file.path(fig_dir, "fig_barplot100_consultation_quintile.png")', file = con, sep = "\n")
cat('fig_violin_quint  <- file.path(fig_dir, "fig_violin_depenses_quintile.png")', file = con, sep = "\n")
cat('fig_violin_milieu <- file.path(fig_dir, "fig_violin_depenses_urbain_rural.png")', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('p_consult <- if (!is.null(tab_test_consult) && "p_value" %in% names(tab_test_consult))', file = con, sep = "\n")
cat('              tab_test_consult$p_value[1] else NA', file = con, sep = "\n")
cat('p_wilcox  <- if (!is.null(tab_wilcox) && "p_value" %in% names(tab_wilcox))', file = con, sep = "\n")
cat('              tab_wilcox$p_value[1] else NA', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

# ---- Page de garde ----
cat('---', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r logo-ansd, fig.align="center", out.width="45%", fig.cap=""}', file = con, sep = "\n")
cat('if (file.exists(logo_ansd)) knitr::include_graphics(logo_ansd)', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('**ANSD --- Agence Nationale de la Statistique et de la Demographie**', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r logo-ensae, fig.align="center", out.width="45%", fig.cap=""}', file = con, sep = "\n")
cat('if (file.exists(logo_ensae)) knitr::include_graphics(logo_ensae)', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('**ENSAE --- Ecole Nationale de la Statistique et de l\'Analyse Economique**', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('---', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('&nbsp;', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('**Rapport d\'analyse statistique ponderee**', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('| | |', file = con, sep = "\n")
cat('|:---|:---|', file = con, sep = "\n")
cat('| **Theme :** | Acces aux services de sante et chocs sanitaires des menages |', file = con, sep = "\n")
cat('| **Donnees :** | Nigeria GHS Panel (W4) |', file = con, sep = "\n")
cat('| **Auteurs :** | RIRADJIM NGARMOUNDOU Tresor ; GUEBEDIANG A NKEN Kadidja |', file = con, sep = "\n")
cat('| **Annee academique :** | 2025--2026 |', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('\\newpage', file = con, sep = "\n")
cat('', file = con, sep = "\n")

# ---- Sections ----
cat('# Resume', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Ce rapport presente une analyse ponderee de l\'acces aux services de sante et des depenses', file = con, sep = "\n")
cat('de sante des menages nigerians a partir de la vague 4 du Nigeria GHS Panel.', file = con, sep = "\n")
cat('L\'objectif est de decrire la morbidite declaree, les types de maladies les plus frequents,', file = con, sep = "\n")
cat('les prestataires consultes, la distribution des depenses de sante et les inegalites eventuelles', file = con, sep = "\n")
cat('selon le milieu de residence ou le niveau de vie.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('La base analytique a ete construite a partir des fichiers individuels, sante et consommation.', file = con, sep = "\n")
cat('Les ponderations d\'enquete ont ete integrees a partir de la variable `wt_wave4` du fichier de', file = con, sep = "\n")
cat('consommation agregee. Les resultats sont presentes en logique ponderee, ce qui permet une', file = con, sep = "\n")
cat('lecture plus representative de la population etudiee.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('\\newpage', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('# Introduction', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('L\'acces aux services de sante constitue une dimension centrale du bien-etre des menages.', file = con, sep = "\n")
cat('Dans les enquetes menages, son etude necessite une attention particuliere a la structure de', file = con, sep = "\n")
cat('l\'echantillon et aux ponderations associees. Une analyse non ponderee risquerait de produire', file = con, sep = "\n")
cat('des resultats biaises ou peu representatifs.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Dans ce travail, nous analysons les episodes de maladie declares, les prestataires de soins', file = con, sep = "\n")
cat('mobilises, les depenses de sante ainsi que certaines disparites selon le milieu de residence', file = con, sep = "\n")
cat('et le niveau de consommation. L\'approche retenue vise a produire des resultats descriptifs', file = con, sep = "\n")
cat('solides et statistiquement coherents.', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('# Source des donnees et construction de la base', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Les donnees proviennent du depot GitHub utilise dans le projet. Les archives ont ete', file = con, sep = "\n")
cat('telechargees, decompressees puis explorees automatiquement pour identifier les fichiers', file = con, sep = "\n")
cat('utiles de la vague 4.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Trois fichiers ont ete mobilises :', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('- le fichier individuel ;', file = con, sep = "\n")
cat('- le fichier sante ;', file = con, sep = "\n")
cat('- le fichier de consommation agregee du menage.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('La ponderation retenue dans l\'analyse est le poids menage `wt_wave4`, extrait de', file = con, sep = "\n")
cat('`totcons_final.dta`. Apres jointure, ce poids est affecte a chaque individu du menage.', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Formulation mathematique des jointures', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Soient :', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('- $I$ : la table des individus ;', file = con, sep = "\n")
cat('- $S$ : la table sante ;', file = con, sep = "\n")
cat('- $C$ : la table consommation du menage.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('La base analytique finale est definie par :', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('$$A = \\left( S \\overset{(hhid,\\,indiv)}{\\bowtie_L} I \\right) \\overset{hhid}{\\bowtie_L} C$$', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('ou la jointure entre sante et individus se fait par $(hhid, indiv)$, puis la jointure', file = con, sep = "\n")
cat('avec la consommation par $hhid$.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Pour chaque individu $i$ du menage $h$, le poids utilise dans l\'analyse est :', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('$$w_{hi} = w_h \\quad \\text{avec} \\quad w_h = wt\\_wave4_h$$', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('# Methodologie', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Les analyses ont ete conduites dans une logique ponderee. Cette approche permet d\'estimer', file = con, sep = "\n")
cat('des proportions, effectifs et statistiques descriptives plus representatifs de la population etudiee.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Les resultats comprennent :', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('- la morbidite selon le sexe et l\'age ;', file = con, sep = "\n")
cat('- les 10 maladies les plus frequentes ;', file = con, sep = "\n")
cat('- les prestataires consultes ;', file = con, sep = "\n")
cat('- la distribution des depenses de sante ;', file = con, sep = "\n")
cat('- le lien entre consultation et quintile de consommation ;', file = con, sep = "\n")
cat('- la comparaison des depenses selon le milieu urbain ou rural.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Lorsque cela est possible, les tests utilises sont coherents avec la logique des enquetes complexes.', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('# Description de la base analytique', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-effectifs}', file = con, sep = "\n")
cat('if (!is.null(tab_effectifs)) {', file = con, sep = "\n")
cat('  kable(tab_effectifs, caption = "Effectifs par analyse", align = "l")', file = con, sep = "\n")
cat('} else { cat("Le tableau des effectifs n\'est pas disponible.") }', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-missing}', file = con, sep = "\n")
cat('if (!is.null(tab_missing)) {', file = con, sep = "\n")
cat('  kable(tab_missing, caption = "Resume des valeurs manquantes", align = "l")', file = con, sep = "\n")
cat('} else { cat("Le tableau des valeurs manquantes n\'est pas disponible.") }', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('# Resultats', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('## Morbidite selon le sexe et le groupe d\'age', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('La morbidite correspond ici a la part des individus ayant declare une maladie ou une blessure.', file = con, sep = "\n")
cat('Le tableau suivant presente cette proportion selon le sexe et le groupe d\'age.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-morbidite}', file = con, sep = "\n")
cat('if (!is.null(tab_morbidite)) {', file = con, sep = "\n")
cat('  kable(tab_morbidite, caption = "Morbidite selon le sexe et le groupe d\'age", align = "l")', file = con, sep = "\n")
cat('} else { cat("Le tableau de morbidite n\'est pas disponible.") }', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r fig-morbidite, fig.cap="Morbidite selon le sexe et le groupe d\'age"}', file = con, sep = "\n")
cat('if (file.exists(fig_morbidite)) knitr::include_graphics(fig_morbidite) else', file = con, sep = "\n")
cat('  cat("La figure de morbidite n\'est pas disponible.")', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Top 10 des maladies declarees', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Cette section presente les maladies les plus frequemment declarees dans l\'echantillon pondere.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-maladies}', file = con, sep = "\n")
cat('if (!is.null(tab_maladies)) {', file = con, sep = "\n")
cat('  kable(tab_maladies, caption = "Top 10 des maladies declarees", align = "l")', file = con, sep = "\n")
cat('} else { cat("Le tableau des maladies n\'est pas disponible.") }', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r fig-maladies, fig.cap="Top 10 des maladies declarees"}', file = con, sep = "\n")
cat('if (file.exists(fig_maladies)) knitr::include_graphics(fig_maladies) else', file = con, sep = "\n")
cat('  cat("La figure des maladies n\'est pas disponible.")', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Prestataires consultes', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Les prestataires consultes permettent de decrire les formes principales de recours aux soins.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-prestataires}', file = con, sep = "\n")
cat('if (!is.null(tab_prestataires)) {', file = con, sep = "\n")
cat('  kable(tab_prestataires, caption = "Prestataires consultes", align = "l")', file = con, sep = "\n")
cat('} else { cat("Le tableau des prestataires n\'est pas disponible.") }', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r fig-prestataires, fig.cap="Distribution des prestataires consultes"}', file = con, sep = "\n")
cat('if (file.exists(fig_prestataires)) knitr::include_graphics(fig_prestataires) else', file = con, sep = "\n")
cat('  cat("La figure des prestataires n\'est pas disponible.")', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Distribution des depenses de sante', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Les depenses de sante sont generalement tres dispersees.', file = con, sep = "\n")
cat('Une visualisation logarithmique permet d\'en ameliorer la lecture.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-deciles}', file = con, sep = "\n")
cat('if (!is.null(tab_deciles)) {', file = con, sep = "\n")
cat('  kable(tab_deciles, caption = "Deciles des depenses de sante", align = "l")', file = con, sep = "\n")
cat('} else { cat("Le tableau des deciles n\'est pas disponible.") }', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r fig-hist-dep, fig.cap="Distribution des depenses de sante (echelle logarithmique)"}', file = con, sep = "\n")
cat('if (file.exists(fig_hist_dep)) knitr::include_graphics(fig_hist_dep) else', file = con, sep = "\n")
cat('  cat("L\'histogramme des depenses n\'est pas disponible.")', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-outliers}', file = con, sep = "\n")
cat('if (!is.null(tab_outliers)) {', file = con, sep = "\n")
cat('  kable(head(tab_outliers, 20),', file = con, sep = "\n")
cat('        caption = "Extrait des valeurs aberrantes des depenses (20 premieres observations)",', file = con, sep = "\n")
cat('        align = "l")', file = con, sep = "\n")
cat('}', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Depenses de sante par prestataire', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Le boxplot suivant permet de visualiser la dispersion des depenses selon le type de prestataire consulte.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r fig-box-dep-prest, fig.cap="Depenses de sante selon le prestataire consulte"}', file = con, sep = "\n")
cat('if (file.exists(fig_box_dep_prest)) knitr::include_graphics(fig_box_dep_prest) else', file = con, sep = "\n")
cat('  cat("La figure des depenses par prestataire n\'est pas disponible.")', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Consultation et quintile de consommation', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('L\'objectif ici est d\'examiner si le recours aux soins varie selon le niveau de consommation du menage.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-contingence}', file = con, sep = "\n")
cat('if (!is.null(tab_contingence)) {', file = con, sep = "\n")
cat('  kable(tab_contingence,', file = con, sep = "\n")
cat('        caption = "Table de contingence : consultation x quintile de consommation",', file = con, sep = "\n")
cat('        align = "l")', file = con, sep = "\n")
cat('} else { cat("La table de contingence n\'est pas disponible.") }', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-prop-consult}', file = con, sep = "\n")
cat('if (!is.null(tab_prop_consult)) {', file = con, sep = "\n")
cat('  kable(tab_prop_consult,', file = con, sep = "\n")
cat('        caption = "Proportions de consultation par quintile de consommation",', file = con, sep = "\n")
cat('        align = "l")', file = con, sep = "\n")
cat('}', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r fig-bar100, fig.cap="Proportions de consultation selon le quintile de consommation"}', file = con, sep = "\n")
cat('if (file.exists(fig_bar100)) knitr::include_graphics(fig_bar100) else', file = con, sep = "\n")
cat('  cat("La figure consultation x quintile n\'est pas disponible.")', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r interp-consult, results="asis"}', file = con, sep = "\n")
cat('if (!is.na(p_consult)) {', file = con, sep = "\n")
cat('  cat("Le test d\'association entre consultation et quintile donne une p-valeur de",', file = con, sep = "\n")
cat('      pval_fr(p_consult), ".",', file = con, sep = "\n")
cat('      ifelse(p_consult < 0.05,', file = con, sep = "\n")
cat('        "On rejette l\'hypothese d\'independance au seuil de 5 % : association significative.",', file = con, sep = "\n")
cat('        "On ne rejette pas l\'hypothese d\'independance au seuil de 5 % : pas d\'association significative."))', file = con, sep = "\n")
cat('}', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Depenses de sante selon le quintile de consommation', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Le graphique suivant compare la distribution des depenses de sante selon les quintiles de consommation.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r fig-violin-quint, fig.cap="Distribution des depenses de sante selon le quintile de consommation"}', file = con, sep = "\n")
cat('if (file.exists(fig_violin_quint)) knitr::include_graphics(fig_violin_quint) else', file = con, sep = "\n")
cat('  cat("La figure des depenses par quintile n\'est pas disponible.")', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Depenses de sante selon le milieu de residence', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Cette section compare les depenses de sante entre menages urbains et ruraux.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r tab-medianes}', file = con, sep = "\n")
cat('if (!is.null(tab_medianes)) {', file = con, sep = "\n")
cat('  kable(tab_medianes,', file = con, sep = "\n")
cat('        caption = "Medianes des depenses de sante selon le milieu de residence",', file = con, sep = "\n")
cat('        align = "l")', file = con, sep = "\n")
cat('} else { cat("Le tableau des medianes par milieu n\'est pas disponible.") }', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r fig-violin-milieu, fig.cap="Distribution des depenses de sante selon le milieu de residence"}', file = con, sep = "\n")
cat('if (file.exists(fig_violin_milieu)) knitr::include_graphics(fig_violin_milieu) else', file = con, sep = "\n")
cat('  cat("La figure des depenses urbain/rural n\'est pas disponible.")', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r interp-wilcox, results="asis"}', file = con, sep = "\n")
cat('if (!is.na(p_wilcox)) {', file = con, sep = "\n")
cat('  cat("Le test de comparaison des depenses urbain/rural donne une p-valeur de",', file = con, sep = "\n")
cat('      pval_fr(p_wilcox), ".",', file = con, sep = "\n")
cat('      ifelse(p_wilcox < 0.05,', file = con, sep = "\n")
cat('        "La difference observee est statistiquement significative au seuil de 5 %.",', file = con, sep = "\n")
cat('        "La difference observee n\'est pas statistiquement significative au seuil de 5 %."))', file = con, sep = "\n")
cat('}', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('# Discussion', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Les resultats obtenus mettent en evidence la diversite des situations sanitaires et des', file = con, sep = "\n")
cat('comportements de recours aux soins. L\'analyse des maladies declarees permet d\'identifier', file = con, sep = "\n")
cat('les affections dominantes, tandis que la distribution des prestataires renseigne sur les', file = con, sep = "\n")
cat('formes de prise en charge privilegiees.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('L\'etude des depenses montre egalement une forte heterogeneite, avec presence de valeurs', file = con, sep = "\n")
cat('extremes et de fortes differences de dispersion selon les groupes. L\'introduction des', file = con, sep = "\n")
cat('ponderations renforce la validite descriptive des resultats, en les replacant dans une', file = con, sep = "\n")
cat('logique de representativite.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('L\'association eventuelle entre recours aux soins et niveau de vie doit etre interpretee', file = con, sep = "\n")
cat('avec prudence mais constitue un axe important pour comprendre les inegalites d\'acces', file = con, sep = "\n")
cat('aux services de sante.', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('# Limites', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Ce travail presente plusieurs limites. D\'abord, les variables de sante peuvent etre', file = con, sep = "\n")
cat('affectees par des biais de memoire ou de declaration. Ensuite, le poids utilise est un', file = con, sep = "\n")
cat('poids menage projete au niveau individuel apres jointure. Enfin, la qualite du rapport', file = con, sep = "\n")
cat('depend de la bonne generation prealable des tableaux et figures produits par les scripts d\'analyse.', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('# Conclusion', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Ce rapport met en evidence l\'interet d\'une approche ponderee pour l\'etude de l\'acces aux', file = con, sep = "\n")
cat('services de sante et des depenses de sante. La prise en compte du poids `wt_wave4` permet', file = con, sep = "\n")
cat('de produire des resultats plus coherents avec la structure reelle de la population couverte', file = con, sep = "\n")
cat('par l\'enquete.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('Sur le plan analytique, le travail decrit la morbidite, les maladies les plus frequentes,', file = con, sep = "\n")
cat('les prestataires consultes et les ecarts de depenses observes selon differentes dimensions', file = con, sep = "\n")
cat('socio-economiques. Sur le plan methodologique, il montre l\'importance d\'integrer les', file = con, sep = "\n")
cat('ponderations et d\'utiliser des sorties bien structurees pour construire un rapport final reproductible.', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('\\newpage', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('# Annexes {-}', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('## Tests statistiques {-}', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r annex-test-consult}', file = con, sep = "\n")
cat('if (!is.null(tab_test_consult)) {', file = con, sep = "\n")
cat('  kable(tab_test_consult,', file = con, sep = "\n")
cat('        caption = "Resultats des tests statistiques : consultation x quintile",', file = con, sep = "\n")
cat('        align = "l")', file = con, sep = "\n")
cat('}', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r annex-wilcox}', file = con, sep = "\n")
cat('if (!is.null(tab_wilcox)) {', file = con, sep = "\n")
cat('  kable(tab_wilcox,', file = con, sep = "\n")
cat('        caption = "Resultat du test de Wilcoxon : depenses de sante urbain/rural",', file = con, sep = "\n")
cat('        align = "l")', file = con, sep = "\n")
cat('}', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Controle de presence des fichiers utilises {-}', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r controle-fichiers}', file = con, sep = "\n")
cat('fichiers <- data.frame(', file = con, sep = "\n")
cat('  Fichier = c(', file = con, sep = "\n")
cat('    "output/tables/table_effectifs_par_analyse.csv",', file = con, sep = "\n")
cat('    "output/tables/table_missing_summary.csv",', file = con, sep = "\n")
cat('    "output/tables/table_morbidite_sexe_age.csv",', file = con, sep = "\n")
cat('    "output/tables/table_top10_maladies.csv",', file = con, sep = "\n")
cat('    "output/tables/table_prestataires.csv",', file = con, sep = "\n")
cat('    "output/tables/table_deciles_depenses_sante.csv",', file = con, sep = "\n")
cat('    "output/tables/table_medianes_depenses_milieu.csv",', file = con, sep = "\n")
cat('    "output/tables/table_outliers_depenses_sante.csv",', file = con, sep = "\n")
cat('    "output/tables/table_contingence_consultation_quintile.csv",', file = con, sep = "\n")
cat('    "output/tables/table_proportions_consultation_quintile.csv",', file = con, sep = "\n")
cat('    "output/tables/table_tests_consultation_quintile.csv",', file = con, sep = "\n")
cat('    "output/tables/table_wilcoxon_urbain_rural.csv",', file = con, sep = "\n")
cat('    "output/figures/fig_morbidite_sexe_age.png",', file = con, sep = "\n")
cat('    "output/figures/fig_top10_maladies.png",', file = con, sep = "\n")
cat('    "output/figures/fig_prestataires.png",', file = con, sep = "\n")
cat('    "output/figures/fig_hist_depenses_log.png",', file = con, sep = "\n")
cat('    "output/figures/fig_boxplot_depenses_prestataire.png",', file = con, sep = "\n")
cat('    "output/figures/fig_barplot100_consultation_quintile.png",', file = con, sep = "\n")
cat('    "output/figures/fig_violin_depenses_quintile.png",', file = con, sep = "\n")
cat('    "output/figures/fig_violin_depenses_urbain_rural.png"', file = con, sep = "\n")
cat('  ),', file = con, sep = "\n")
cat('  Presence = c(', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_effectifs_par_analyse.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_missing_summary.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_morbidite_sexe_age.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_top10_maladies.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_prestataires.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_deciles_depenses_sante.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_medianes_depenses_milieu.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_outliers_depenses_sante.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_contingence_consultation_quintile.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_proportions_consultation_quintile.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_tests_consultation_quintile.csv")),', file = con, sep = "\n")
cat('    file.exists(file.path(tab_dir, "table_wilcoxon_urbain_rural.csv")),', file = con, sep = "\n")
cat('    file.exists(fig_morbidite),', file = con, sep = "\n")
cat('    file.exists(fig_maladies),', file = con, sep = "\n")
cat('    file.exists(fig_prestataires),', file = con, sep = "\n")
cat('    file.exists(fig_hist_dep),', file = con, sep = "\n")
cat('    file.exists(fig_box_dep_prest),', file = con, sep = "\n")
cat('    file.exists(fig_bar100),', file = con, sep = "\n")
cat('    file.exists(fig_violin_quint),', file = con, sep = "\n")
cat('    file.exists(fig_violin_milieu)', file = con, sep = "\n")
cat('  )', file = con, sep = "\n")
cat(')', file = con, sep = "\n")
cat('kable(fichiers,', file = con, sep = "\n")
cat('      caption = "Verification des fichiers utilises dans le rapport",', file = con, sep = "\n")
cat('      align   = c("l", "c"))', file = con, sep = "\n")
cat('```', file = con, sep = "\n")
cat('', file = con, sep = "\n")

cat('## Informations de session {-}', file = con, sep = "\n")
cat('', file = con, sep = "\n")
cat('```{r session-info}', file = con, sep = "\n")
cat('sessionInfo()', file = con, sep = "\n")
cat('```', file = con, sep = "\n")

close(con)
cat("   OK rapport_analyse3.Rmd ecrit dans", report_dir, "\n")

# ---- 5. Compilation --------------------------------------
cat("   Compilation du rapport en cours...\n")

rmarkdown::render(
  input       = rmd_file,
  output_file = output_file,
  encoding    = "UTF-8",
  quiet       = FALSE
)

cat("   OK Rapport genere :", output_file, "\n")